"""GoatFlow Python SDK.

    >>> from goatflow_sdk import GoatflowClient
    >>> async with GoatflowClient.with_api_key("https://goatflow.example.com", "gf_...") as client:
    ...     tickets = await client.tickets.list(status="open")
    ...     print(tickets.pagination.total)
"""

from .auth import APIKeyAuth, Authenticator, JWTAuth, NoAuth
from .client import GoatflowClient
from .exceptions import (
    AuthenticationError,
    ForbiddenError,
    GoatflowError,
    NetworkError,
    NotFoundError,
    RateLimitError,
    ResponseShapeError,
    ServerError,
    TimeoutError,
    UnauthorizedError,
)
from .models import (
    Article,
    ArticleAttachment,
    ArticleCreateRequest,
    ArticleList,
    ArticleUpdate,
    ArticleUpdateRequest,
    CreatedTicket,
    CreatedUser,
    CurrentUser,
    DashboardStatistics,
    GroupRef,
    Health,
    TokenPair,
    Pagination,
    Queue,
    ReopenResult,
    SearchHit,
    SearchQuery,
    SearchResults,
    Ticket,
    TicketCreateRequest,
    TicketList,
    TicketRecord,
    TicketSummary,
    TicketUpdateRequest,
    User,
    UserCreateRequest,
    UserGroup,
    UserList,
    UserUpdateRequest,
    Webhook,
    WebhookDelivery,
    WebhookRequest,
)

__version__ = "1.0.0"

__all__ = [
    "GoatflowClient",
    "APIKeyAuth",
    "Authenticator",
    "JWTAuth",
    "NoAuth",
    "AuthenticationError",
    "ForbiddenError",
    "GoatflowError",
    "NetworkError",
    "NotFoundError",
    "RateLimitError",
    "ResponseShapeError",
    "ServerError",
    "TimeoutError",
    "UnauthorizedError",
    "Article",
    "ArticleAttachment",
    "ArticleCreateRequest",
    "ArticleList",
    "ArticleUpdate",
    "ArticleUpdateRequest",
    "CreatedTicket",
    "CreatedUser",
    "CurrentUser",
    "DashboardStatistics",
    "GroupRef",
    "Health",
    "TokenPair",
    "Pagination",
    "Queue",
    "ReopenResult",
    "SearchHit",
    "SearchQuery",
    "SearchResults",
    "Ticket",
    "TicketCreateRequest",
    "TicketList",
    "TicketRecord",
    "TicketSummary",
    "TicketUpdateRequest",
    "User",
    "UserCreateRequest",
    "UserGroup",
    "UserList",
    "UserUpdateRequest",
    "Webhook",
    "WebhookDelivery",
    "WebhookRequest",
]
