-- PostgreSQL/MySQL schema parity (DB-agnostic sweep).
-- MySQL is the reference definition. A column-by-column comparison of fully
-- migrated databases (types, widths, nullability, defaults, PRIMARY/UNIQUE keys)
-- found no PostgreSQL column that needs realigning:
--   * Flag columns that are BOOLEAN here and TINYINT(1) in MySQL
--     (gk_custom_field_def.required, gk_identity_provider.enabled/auto_provision,
--     gk_plugin_ui.enabled, gk_totp_pending_session.is_customer,
--     gk_user_organisation.is_default) stay BOOLEAN: the Go code writes Go bool
--     values to all of them. Portable SQL compares them with TRUE/FALSE literals
--     or bound bool parameters, never with 1/0.
--   * SMALLINT id columns (ticket_state.id, valid.id, ...) are SMALLINT on both
--     drivers.
-- Further alignments found during the sweep follow, idempotently.

-- Foreign keys: migrations/mysql defines the OTRS core foreign keys
-- (FK_<table>_<col>_<refcol>); migrations/postgres only had the gk_* ones.
-- Add every MySQL foreign key that PostgreSQL lacks, same name, columns and
-- ON DELETE rule. Each is added NOT VALID (enforced for new writes at once,
-- never blocks the upgrade) and then validated; existing orphan rows only leave
-- that constraint unvalidated with a NOTICE.
DO $$
DECLARE
    fk text[];
BEGIN
    FOREACH fk SLICE 1 IN ARRAY ARRAY[
        ['acl', 'FK_acl_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['acl', 'FK_acl_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['acl', 'FK_acl_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['article', 'FK_article_article_sender_type_id_id', 'article_sender_type_id', 'article_sender_type', 'id', 'RESTRICT'],
        ['article', 'FK_article_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['article', 'FK_article_communication_channel_id_id', 'communication_channel_id', 'communication_channel', 'id', 'RESTRICT'],
        ['article', 'FK_article_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article', 'FK_article_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['article_data_mime', 'FK_article_data_mime_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_data_mime', 'FK_article_data_mime_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime', 'FK_article_data_mime_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime_attachment', 'FK_article_data_mime_attachment_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_data_mime_attachment', 'FK_article_data_mime_attachment_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime_attachment', 'FK_article_data_mime_attachment_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime_plain', 'FK_article_data_mime_plain_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_data_mime_plain', 'FK_article_data_mime_plain_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime_plain', 'FK_article_data_mime_plain_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article_data_mime_send_error', 'FK_article_data_mime_send_error_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_data_otrs_chat', 'FK_article_data_otrs_chat_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_flag', 'FK_article_flag_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_flag', 'FK_article_flag_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article_search_index', 'FK_article_search_index_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['article_search_index', 'FK_article_search_index_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['article_sender_type', 'FK_article_sender_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['article_sender_type', 'FK_article_sender_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['article_sender_type', 'FK_article_sender_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['auto_response', 'FK_auto_response_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['auto_response', 'FK_auto_response_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['auto_response', 'FK_auto_response_system_address_id_id', 'system_address_id', 'system_address', 'id', 'RESTRICT'],
        ['auto_response', 'FK_auto_response_type_id_id', 'type_id', 'auto_response_type', 'id', 'RESTRICT'],
        ['auto_response', 'FK_auto_response_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['auto_response_type', 'FK_auto_response_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['auto_response_type', 'FK_auto_response_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['auto_response_type', 'FK_auto_response_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['calendar', 'FK_calendar_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['calendar', 'FK_calendar_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['calendar', 'FK_calendar_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['calendar', 'FK_calendar_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['calendar_appointment', 'FK_calendar_appointment_calendar_id_id', 'calendar_id', 'calendar', 'id', 'RESTRICT'],
        ['calendar_appointment', 'FK_calendar_appointment_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['calendar_appointment', 'FK_calendar_appointment_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['calendar_appointment', 'FK_calendar_appointment_parent_id_id', 'parent_id', 'calendar_appointment', 'id', 'RESTRICT'],
        ['calendar_appointment_ticket', 'FK_calendar_appointment_ticket_appointment_id_id', 'appointment_id', 'calendar_appointment', 'id', 'RESTRICT'],
        ['calendar_appointment_ticket', 'FK_calendar_appointment_ticket_calendar_id_id', 'calendar_id', 'calendar', 'id', 'RESTRICT'],
        ['calendar_appointment_ticket', 'FK_calendar_appointment_ticket_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['cloud_service_config', 'FK_cloud_service_config_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['cloud_service_config', 'FK_cloud_service_config_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['cloud_service_config', 'FK_cloud_service_config_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['communication_channel', 'FK_communication_channel_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['communication_channel', 'FK_communication_channel_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['communication_channel', 'FK_communication_channel_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['communication_log_obj_lookup', 'FK_communication_log_obj_lookup_communication_log_object_i0f', 'communication_log_object_id', 'communication_log_object', 'id', 'RESTRICT'],
        ['communication_log_object', 'FK_communication_log_object_communication_id_id', 'communication_id', 'communication_log', 'id', 'RESTRICT'],
        ['communication_log_object_entry', 'FK_communication_log_object_entry_communication_log_objectaa', 'communication_log_object_id', 'communication_log_object', 'id', 'RESTRICT'],
        ['customer_user', 'FK_customer_user_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['customer_user', 'FK_customer_user_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['customer_user', 'FK_customer_user_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['customer_user_customer', 'FK_customer_user_customer_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['customer_user_customer', 'FK_customer_user_customer_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['dynamic_field', 'FK_dynamic_field_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['dynamic_field', 'FK_dynamic_field_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['dynamic_field', 'FK_dynamic_field_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['dynamic_field_value', 'FK_dynamic_field_value_field_id_id', 'field_id', 'dynamic_field', 'id', 'RESTRICT'],
        ['follow_up_possible', 'FK_follow_up_possible_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['follow_up_possible', 'FK_follow_up_possible_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['follow_up_possible', 'FK_follow_up_possible_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['form_draft', 'FK_form_draft_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['form_draft', 'FK_form_draft_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['gi_debugger_entry', 'FK_gi_debugger_entry_webservice_id_id', 'webservice_id', 'gi_webservice_config', 'id', 'RESTRICT'],
        ['gi_debugger_entry_content', 'FK_gi_debugger_entry_content_gi_debugger_entry_id_id', 'gi_debugger_entry_id', 'gi_debugger_entry', 'id', 'RESTRICT'],
        ['gi_webservice_config', 'FK_gi_webservice_config_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['gi_webservice_config', 'FK_gi_webservice_config_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['gi_webservice_config', 'FK_gi_webservice_config_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['gi_webservice_config_history', 'FK_gi_webservice_config_history_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['gi_webservice_config_history', 'FK_gi_webservice_config_history_config_id_id', 'config_id', 'gi_webservice_config', 'id', 'RESTRICT'],
        ['gi_webservice_config_history', 'FK_gi_webservice_config_history_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['group_customer', 'FK_group_customer_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['group_customer', 'FK_group_customer_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['group_customer', 'FK_group_customer_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['group_customer_user', 'FK_group_customer_user_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['group_customer_user', 'FK_group_customer_user_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['group_customer_user', 'FK_group_customer_user_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['group_role', 'FK_group_role_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['group_role', 'FK_group_role_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['group_role', 'FK_group_role_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['group_role', 'FK_group_role_role_id_id', 'role_id', 'roles', 'id', 'RESTRICT'],
        ['group_user', 'FK_group_user_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['group_user', 'FK_group_user_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['group_user', 'FK_group_user_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['group_user', 'FK_group_user_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['groups', 'FK_groups_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['groups', 'FK_groups_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['groups', 'FK_groups_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['link_relation', 'FK_link_relation_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['link_relation', 'FK_link_relation_source_object_id_id', 'source_object_id', 'link_object', 'id', 'RESTRICT'],
        ['link_relation', 'FK_link_relation_state_id_id', 'state_id', 'link_state', 'id', 'RESTRICT'],
        ['link_relation', 'FK_link_relation_target_object_id_id', 'target_object_id', 'link_object', 'id', 'RESTRICT'],
        ['link_relation', 'FK_link_relation_type_id_id', 'type_id', 'link_type', 'id', 'RESTRICT'],
        ['link_state', 'FK_link_state_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['link_state', 'FK_link_state_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['link_state', 'FK_link_state_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['link_type', 'FK_link_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['link_type', 'FK_link_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['link_type', 'FK_link_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['mail_account', 'FK_mail_account_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['mail_account', 'FK_mail_account_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['mail_account', 'FK_mail_account_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['mail_queue', 'FK_mail_queue_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['notification_event', 'FK_notification_event_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['notification_event', 'FK_notification_event_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['notification_event', 'FK_notification_event_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['notification_event_item', 'FK_notification_event_item_notification_id_id', 'notification_id', 'notification_event', 'id', 'RESTRICT'],
        ['notification_event_message', 'FK_notification_event_message_notification_id_id', 'notification_id', 'notification_event', 'id', 'RESTRICT'],
        ['package_repository', 'FK_package_repository_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['package_repository', 'FK_package_repository_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['permission_groups', 'FK_permission_groups_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['permission_groups', 'FK_permission_groups_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['permission_groups', 'FK_permission_groups_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['personal_queues', 'FK_personal_queues_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['personal_queues', 'FK_personal_queues_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['personal_services', 'FK_personal_services_service_id_id', 'service_id', 'service', 'id', 'RESTRICT'],
        ['personal_services', 'FK_personal_services_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['pm_activity', 'FK_pm_activity_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['pm_activity', 'FK_pm_activity_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['pm_activity_dialog', 'FK_pm_activity_dialog_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['pm_activity_dialog', 'FK_pm_activity_dialog_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['pm_process', 'FK_pm_process_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['pm_process', 'FK_pm_process_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['pm_transition', 'FK_pm_transition_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['pm_transition', 'FK_pm_transition_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['pm_transition_action', 'FK_pm_transition_action_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['pm_transition_action', 'FK_pm_transition_action_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_follow_up_id_id', 'follow_up_id', 'follow_up_possible', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_salutation_id_id', 'salutation_id', 'salutation', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_signature_id_id', 'signature_id', 'signature', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_system_address_id_id', 'system_address_id', 'system_address', 'id', 'RESTRICT'],
        ['queue', 'FK_queue_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['queue_auto_response', 'FK_queue_auto_response_auto_response_id_id', 'auto_response_id', 'auto_response', 'id', 'RESTRICT'],
        ['queue_auto_response', 'FK_queue_auto_response_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['queue_auto_response', 'FK_queue_auto_response_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['queue_auto_response', 'FK_queue_auto_response_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['queue_preferences', 'FK_queue_preferences_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['queue_standard_template', 'FK_queue_standard_template_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['queue_standard_template', 'FK_queue_standard_template_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['queue_standard_template', 'FK_queue_standard_template_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['queue_standard_template', 'FK_queue_standard_template_standard_template_id_id', 'standard_template_id', 'standard_template', 'id', 'RESTRICT'],
        ['role_user', 'FK_role_user_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['role_user', 'FK_role_user_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['role_user', 'FK_role_user_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['roles', 'FK_roles_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['roles', 'FK_roles_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['roles', 'FK_roles_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['salutation', 'FK_salutation_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['salutation', 'FK_salutation_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['salutation', 'FK_salutation_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['service', 'FK_service_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['service', 'FK_service_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['service_customer_user', 'FK_service_customer_user_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['service_customer_user', 'FK_service_customer_user_service_id_id', 'service_id', 'service', 'id', 'RESTRICT'],
        ['service_preferences', 'FK_service_preferences_service_id_id', 'service_id', 'service', 'id', 'RESTRICT'],
        ['service_sla', 'FK_service_sla_service_id_id', 'service_id', 'service', 'id', 'RESTRICT'],
        ['service_sla', 'FK_service_sla_sla_id_id', 'sla_id', 'sla', 'id', 'RESTRICT'],
        ['signature', 'FK_signature_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['signature', 'FK_signature_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['signature', 'FK_signature_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['sla', 'FK_sla_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['sla', 'FK_sla_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sla_preferences', 'FK_sla_preferences_sla_id_id', 'sla_id', 'sla', 'id', 'RESTRICT'],
        ['smime_signer_cert_relations', 'FK_smime_signer_cert_relations_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['smime_signer_cert_relations', 'FK_smime_signer_cert_relations_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['standard_attachment', 'FK_standard_attachment_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['standard_attachment', 'FK_standard_attachment_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['standard_attachment', 'FK_standard_attachment_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['standard_template', 'FK_standard_template_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['standard_template', 'FK_standard_template_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['standard_template', 'FK_standard_template_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['standard_template_attachment', 'FK_standard_template_attachment_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['standard_template_attachment', 'FK_standard_template_attachment_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['standard_template_attachment', 'FK_standard_template_attachment_standard_attachment_id_id', 'standard_attachment_id', 'standard_attachment', 'id', 'RESTRICT'],
        ['standard_template_attachment', 'FK_standard_template_attachment_standard_template_id_id', 'standard_template_id', 'standard_template', 'id', 'RESTRICT'],
        ['sysconfig_default', 'FK_sysconfig_default_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_default', 'FK_sysconfig_default_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_default', 'FK_sysconfig_default_exclusive_lock_user_id_id', 'exclusive_lock_user_id', 'users', 'id', 'RESTRICT'],
        ['sysconfig_default_version', 'FK_sysconfig_default_version_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_default_version', 'FK_sysconfig_default_version_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_default_version', 'FK_sysconfig_default_version_sysconfig_default_id_id', 'sysconfig_default_id', 'sysconfig_default', 'id', 'RESTRICT'],
        ['sysconfig_deployment', 'FK_sysconfig_deployment_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_deployment', 'FK_sysconfig_deployment_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['sysconfig_deployment_lock', 'FK_sysconfig_deployment_lock_exclusive_lock_user_id_id', 'exclusive_lock_user_id', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified', 'FK_sysconfig_modified_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified', 'FK_sysconfig_modified_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified', 'FK_sysconfig_modified_sysconfig_default_id_id', 'sysconfig_default_id', 'sysconfig_default', 'id', 'RESTRICT'],
        ['sysconfig_modified', 'FK_sysconfig_modified_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified_version', 'FK_sysconfig_modified_version_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified_version', 'FK_sysconfig_modified_version_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['sysconfig_modified_version', 'FK_sysconfig_modified_version_sysconfig_default_version_idaf', 'sysconfig_default_version_id', 'sysconfig_default_version', 'id', 'RESTRICT'],
        ['sysconfig_modified_version', 'FK_sysconfig_modified_version_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['system_address', 'FK_system_address_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['system_address', 'FK_system_address_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['system_address', 'FK_system_address_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['system_data', 'FK_system_data_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['system_data', 'FK_system_data_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['system_maintenance', 'FK_system_maintenance_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['system_maintenance', 'FK_system_maintenance_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['system_maintenance', 'FK_system_maintenance_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_responsible_user_id_id', 'responsible_user_id', 'users', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_service_id_id', 'service_id', 'service', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_sla_id_id', 'sla_id', 'sla', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_ticket_lock_id_id', 'ticket_lock_id', 'ticket_lock_type', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_ticket_priority_id_id', 'ticket_priority_id', 'ticket_priority', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_ticket_state_id_id', 'ticket_state_id', 'ticket_state', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_type_id_id', 'type_id', 'ticket_type', 'id', 'RESTRICT'],
        ['ticket', 'FK_ticket_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['ticket_flag', 'FK_ticket_flag_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_flag', 'FK_ticket_flag_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_history_type_id_id', 'history_type_id', 'ticket_history_type', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_owner_id_id', 'owner_id', 'users', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_priority_id_id', 'priority_id', 'ticket_priority', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_state_id_id', 'state_id', 'ticket_state', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['ticket_history', 'FK_ticket_history_type_id_id', 'type_id', 'ticket_type', 'id', 'RESTRICT'],
        ['ticket_history_type', 'FK_ticket_history_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_history_type', 'FK_ticket_history_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_history_type', 'FK_ticket_history_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['ticket_index', 'FK_ticket_index_group_id_id', 'group_id', 'groups', 'id', 'RESTRICT'],
        ['ticket_index', 'FK_ticket_index_queue_id_id', 'queue_id', 'queue', 'id', 'RESTRICT'],
        ['ticket_index', 'FK_ticket_index_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['ticket_lock_index', 'FK_ticket_lock_index_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['ticket_lock_type', 'FK_ticket_lock_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_lock_type', 'FK_ticket_lock_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_lock_type', 'FK_ticket_lock_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['ticket_priority', 'FK_ticket_priority_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_priority', 'FK_ticket_priority_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_state', 'FK_ticket_state_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_state', 'FK_ticket_state_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_state', 'FK_ticket_state_type_id_id', 'type_id', 'ticket_state_type', 'id', 'RESTRICT'],
        ['ticket_state', 'FK_ticket_state_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['ticket_state_type', 'FK_ticket_state_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_state_type', 'FK_ticket_state_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_type', 'FK_ticket_type_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_type', 'FK_ticket_type_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_type', 'FK_ticket_type_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['ticket_watcher', 'FK_ticket_watcher_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['ticket_watcher', 'FK_ticket_watcher_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['ticket_watcher', 'FK_ticket_watcher_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['ticket_watcher', 'FK_ticket_watcher_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['time_accounting', 'FK_time_accounting_article_id_id', 'article_id', 'article', 'id', 'RESTRICT'],
        ['time_accounting', 'FK_time_accounting_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['time_accounting', 'FK_time_accounting_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['time_accounting', 'FK_time_accounting_ticket_id_id', 'ticket_id', 'ticket', 'id', 'RESTRICT'],
        ['user_preferences', 'FK_user_preferences_user_id_id', 'user_id', 'users', 'id', 'RESTRICT'],
        ['users', 'FK_users_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['users', 'FK_users_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['users', 'FK_users_valid_id_id', 'valid_id', 'valid', 'id', 'RESTRICT'],
        ['valid', 'FK_valid_change_by_id', 'change_by', 'users', 'id', 'RESTRICT'],
        ['valid', 'FK_valid_create_by_id', 'create_by', 'users', 'id', 'RESTRICT'],
        ['virtual_fs_preferences', 'FK_virtual_fs_preferences_virtual_fs_id_id', 'virtual_fs_id', 'virtual_fs', 'id', 'RESTRICT']
    ] LOOP
        -- fk = {table, constraint, columns, ref_table, ref_columns, on_delete}
        IF to_regclass(quote_ident(fk[1])) IS NULL OR to_regclass(quote_ident(fk[4])) IS NULL THEN
            CONTINUE;
        END IF;
        IF EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = fk[2] AND conrelid = to_regclass(quote_ident(fk[1]))) THEN
            CONTINUE;
        END IF;
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (%I) REFERENCES %I (%I) ON DELETE %s ON UPDATE RESTRICT NOT VALID',
            fk[1], fk[2], fk[3], fk[4], fk[5], fk[6]);
        BEGIN
            EXECUTE format('ALTER TABLE %I VALIDATE CONSTRAINT %I', fk[1], fk[2]);
        EXCEPTION WHEN foreign_key_violation THEN
            RAISE NOTICE 'foreign key % on % left NOT VALID: existing rows violate it', fk[2], fk[1];
        END;
    END LOOP;
END $$;
